import {User, Topic, Module, Note, Comment} from "@/app/shared/types";
// Mock Data

export const users = [
  {
    id: "user-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    contributions: 1,
    topics: ["topic-1", "topic-2"],
    notes: ["note-1", "note-2", "note-3"],
    savedTopics: ["topic-3"],
    savedModules: ["module-5"],
    savedNotes: ["note-4"],
  },
  {
    id: "user-2",
    name: "Bob Smith",
    email: "bob@example.com",
    contributions: 1,
    topics: ["topic-3"],
    notes: ["note-4", "note-5"],
    savedTopics: ["topic-1"],
    savedModules: ["module-2"],
    savedNotes: ["note-6"],
  },
  {
    id: "user-3",
    name: "Charlie Davis",
    email: "charlie@example.com",
    contributions: 1,
    topics: ["topic-4"],
    notes: ["note-6", "note-7", "note-8"],
    savedTopics: ["topic-2"],
    savedModules: ["module-7"],
    savedNotes: ["note-1"],
  },
];

export const comments = [
  {
    id: "comment-1",
    note: "note-1",
    author: "user-2",
    body: "Great note!",
    likes: 2,
  },
  {
    id: "comment-2",
    note: "note-2",
    author: "user-3",
    body: "Very helpful.",
    likes: 1,
  },
  {
    id: "comment-3",
    note: "note-3",
    author: "user-1",
    body: "Interesting point!",
    likes: 4,
  },
  {
    id: "comment-4",
    note: "note-4",
    author: "user-3",
    body: "Thanks for sharing.",
    likes: 3,
  },
  {
    id: "comment-5",
    note: "note-5",
    author: "user-1",
    body: "Clear explanation.",
    likes: 5,
  },
  {
    id: "comment-6",
    note: "note-6",
    author: "user-2",
    body: "Could use more detail.",
    likes: 0,
  },
  {
    id: "comment-7",
    note: "note-7",
    author: "user-1",
    body: "Loved this!",
    likes: 6,
  },
  {
    id: "comment-8",
    note: "note-8",
    author: "user-2",
    body: "Nice breakdown.",
    likes: 2,
  },
];

export const notes = [
  {
    id: "note-1",
    title: "Note 1",
    author: "user-1",
    body: "Content for note 1",
    status: "Published",
    saves: 3,
    contributors: ["user-2"],
    comments: ["comment-1"],
  },
  {
    id: "note-2",
    title: "Note 2",
    author: "user-1",
    body: "Content for note 2",
    status: "Published",
    saves: 2,
    contributors: ["user-3"],
    comments: ["comment-2"],
  },
  {
    id: "note-3",
    title: "Note 3",
    author: "user-1",
    body: "Content for note 3",
    status: "Draft",
    saves: 1,
    contributors: ["user-2"],
    comments: ["comment-3"],
  },
  {
    id: "note-4",
    title: "Note 4",
    author: "user-2",
    body: "Content for note 4",
    status: "Published",
    saves: 4,
    contributors: ["user-1"],
    comments: ["comment-4"],
  },
  {
    id: "note-5",
    title: "Note 5",
    author: "user-2",
    body: "Content for note 5",
    status: "Archived",
    saves: 1,
    contributors: ["user-3"],
    comments: ["comment-5"],
  },
  {
    id: "note-6",
    title: "Note 6",
    author: "user-3",
    body: "Content for note 6",
    status: "Published",
    saves: 5,
    contributors: ["user-2"],
    comments: ["comment-6"],
  },
  {
    id: "note-7",
    title: "Note 7",
    author: "user-3",
    body: "Content for note 7",
    status: "Draft",
    saves: 0,
    contributors: ["user-1"],
    comments: ["comment-7"],
  },
  {
    id: "note-8",
    title: "Note 8",
    author: "user-3",
    body: "Content for note 8",
    status: "Published",
    saves: 6,
    contributors: ["user-2"],
    comments: ["comment-8"],
  },
];

export const modules = [
  {
    id: "module-1",
    title: "Module 1",
    description: "Intro to Science",
    saves: 2,
    status: "Published",
    notes: ["note-1", "note-2"],
    contributors: ["user-1"],
  },
  {
    id: "module-2",
    title: "Module 2",
    description: "Advanced Science",
    saves: 3,
    status: "Published",
    notes: ["note-3", "note-4"],
    contributors: ["user-2"],
  },
  {
    id: "module-3",
    title: "Module 3",
    description: "Science Lab",
    saves: 4,
    status: "Archived",
    notes: ["note-5", "note-6"],
    contributors: ["user-3"],
  },
  {
    id: "module-4",
    title: "Module 4",
    description: "Intro to Literature",
    saves: 1,
    status: "Published",
    notes: ["note-7", "note-8"],
    contributors: ["user-1"],
  },
  {
    id: "module-5",
    title: "Module 5",
    description: "Poetry",
    saves: 2,
    status: "Archived",
    notes: ["note-1", "note-2"],
    contributors: ["user-2"],
  },
  {
    id: "module-6",
    title: "Module 6",
    description: "Novels",
    saves: 5,
    status: "Published",
    notes: ["note-3", "note-4"],
    contributors: ["user-3"],
  },
  {
    id: "module-7",
    title: "Module 7",
    description: "Drama",
    saves: 0,
    status: "Draft",
    notes: ["note-5", "note-6"],
    contributors: ["user-1"],
  },
  {
    id: "module-8",
    title: "Module 8",
    description: "Modern Literature",
    saves: 6,
    status: "Published",
    notes: ["note-7", "note-8"],
    contributors: ["user-2"],
  },
  {
    id: "module-9",
    title: "Module 9",
    description: "Comparative Lit",
    saves: 2,
    status: "Archived",
    notes: ["note-1", "note-2"],
    contributors: ["user-3"],
  },
  {
    id: "module-10",
    title: "Module 10",
    description: "History of Science",
    saves: 7,
    status: "Published",
    notes: ["note-3", "note-4"],
    contributors: ["user-1"],
  },
  {
    id: "module-11",
    title: "Module 11",
    description: "Experiments",
    saves: 3,
    status: "Published",
    notes: ["note-5", "note-6"],
    contributors: ["user-2"],
  },
  {
    id: "module-12",
    title: "Module 12",
    description: "Future Science",
    saves: 1,
    status: "Draft",
    notes: ["note-7", "note-8"],
    contributors: ["user-3"],
  },
];

export const topics = [
  {
    id: "topic-1",
    title: "Physics Basics",
    description: "Understanding physics fundamentals",
    category: "Science",
    status: "Published",
    visibility: "Public",
    saves: 10,
    joins: 5,
    modules: ["module-1", "module-2", "module-3"],
    moderators: ["user-2"],
    owner: "user-1",
  },
  {
    id: "topic-2",
    title: "World Literature",
    description: "Exploring global classics",
    category: "Literature",
    status: "Archived",
    visibility: "Private",
    saves: 6,
    joins: 3,
    modules: ["module-4", "module-5", "module-6"],
    moderators: ["user-3"],
    owner: "user-1",
  },
  {
    id: "topic-3",
    title: "Chemistry Insights",
    description: "Deep dive into chemistry",
    category: "Science",
    status: "Published",
    visibility: "Public",
    saves: 8,
    joins: 4,
    modules: ["module-7", "module-8", "module-9"],
    moderators: ["user-1"],
    owner: "user-2",
  },
  {
    id: "topic-4",
    title: "Biology Discoveries",
    description: "Latest in biology research",
    category: "Science",
    status: "Published",
    visibility: "Private",
    saves: 12,
    joins: 7,
    modules: ["module-10", "module-11", "module-12"],
    moderators: ["user-2"],
    owner: "user-3",
  },
];
